eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://my-sql-db.cwp68g2us6bn.us-east-1.rds.amazonaws.com:3306/restaurantdb
    password: A$hburnV1rg1n1a
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect